steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Set up JDK 17
    uses: actions/setup-java@v2
    with:
      java-version: '17'
      distribution: 'adopt'

  - name: Setup network and MongoDB
    run: |
      docker network create --driver bridge se-methods
      docker pull mongo
      docker run -d --name mongo-dbserver --network se-methods mongo

  - name: Build with Maven
    run: mvn package

  - name: Build Docker image
    run: docker build -t se_methods .

  - name: Run container
    run: docker run --network se-methods --name devopscontainer -d se_methods

  - name: View logs
    run: docker logs devopscontainer
